### ISSUE TITLE
what purpose pyqt6 is serving in this package?  I thouth it is only GUI cross platform and we do not have GUI? 

### ISSUE THREAD

**Issue by smilesun** [Alex-Markham/causalspyne-expt#2]
https://github.com/Alex-Markham/causalspyne-expt/blob/e92ca324a3c4464233f8bdf573e947a9f0d523bc/pyproject.toml#L12

**Comment by Alex-Markham** [comment]
Not sure how it got there, actually. You should be able to remove it with `uv remove pyqt6` (and then you can push the updated `pyproject.toml` and `uv.lock`), or you can wait a few mins for me to do it and update the repo

**Comment by smilesun** [comment]
It is not for important for now since I make it working already I
downgraded the version

**Comment by Alex-Markham** [comment]
ea107eb150ba1fea9bf1b3f582711828168c6842
